### ISSUE TITLE
ST-4 upload issue

### ISSUE THREAD

**Issue by gary143616** [kevinferrare/arduino-st4#2]
I have uploaded the software and received a"finished uploading" message, the red LED is on, the green LED stopped flashing  but the hardware does not seem to respond to commands, COMMAND+# does not turn the LED on or off, the only change is that a yellow LED gives one fast flick when the command is executed.
I also have a window with the following message:
void setup() {
  // put your setup code here, to run once:

}

void loop() {
  // put your main code here, to run repeatedly:
This is my first contact with Arduino and uploading code so I have no idea what to do next.
I would very much appreciate some assistance.
Thanks,
Gary

**Comment by kevinferrare** [comment]
Hello Gary,

It seems that you are uploading an empty arduino program instead of the sketch I link in the installation steps.

If this is the first time you use an arduino, I recommend that you try to upload the examples built-in with the arduino IDE software.
There are a lot of resources on the internet on how to do so.
You could start with the arduino forums.
